import { useMemo, useState } from 'react';
import { Clapperboard, Loader2, Plus, Trash2, ArrowUp, ArrowDown } from 'lucide-react';
import { CardTitle, ChipToggle, Field, Banner } from '../components/ui';
import { NotConnected, ContractCard } from '../components/ui/studio';
import { VIDEO_STATES } from '../data/studio';
import { api, ApiError } from '../api/client';
import { formatDuration } from '../lib/planner';
import { slotValues } from '../lib/facts';
import { useStore } from '../state/store';

// Agnes video: 4 to 12 s per clip, queued at 1 request per minute on the Free tier, list price $0.025/s at 720P
// (Flash is free for now). Latency per clip is NOT calibrated yet, so the queue time below is an estimate.
const MIN_S = 4;
const MAX_S = 12;
const RPM = 1;
const EST_CLIP_S = 150; // placeholder until the video service reports real timings
const USD_INR = 88;
const USD_PER_S = 0.025;

const REQUEST = `POST /video/reel
{
  "campaign_id": "c1", "facts_version": 2,
  "aspect_ratio": "9:16", "size": "720P",
  "shots": [ { "prompt": "steaming filter coffee close-up, no text", "seconds": 4, "mode": "text" },
             { "prompt": "...", "seconds": 8, "mode": "reference", "images": ["upload_id"] } ],
  "overlay": { "price": "from the locked facts", "cta": "visit and WhatsApp" },
  "stitch": "ffmpeg"
}`;
const RESPONSE = `202 { "reel_id": "r_41", "job_ids": ["j1","j2","j3","j4"] }
GET /jobs/j1 -> { "status": "queued" | "in_progress" | "completed" | "failed", "url": "https://...", "seconds": 4 }
GET /video/r_41 -> { "status": "...", "stitched_url": "https://...", "labelled_fallback": false }
// Offer text and prices are stamped by code from the locked facts, never drawn by the video model.
// Any saved fallback clip must set labelled_fallback=true so the UI can say "saved demo output".`;

const ASPECTS = [{ id: '9:16', label: '9:16 Reels' }, { id: '1:1', label: '1:1 Feed' }, { id: '16:9', label: '16:9 Wide' }];

// S19: shots, length, cost and queue time are real maths; generation is the video team's service.
const Video = () => {
  const { state, dispatch, approvedFacts } = useStore();
  const V = state.video;
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const set = (patch) => dispatch({ type: 'SET_VIDEO', patch });
  const sv = slotValues(approvedFacts.json, 'en');

  const stats = useMemo(() => {
    const total = V.shots.reduce((a, s) => a + Number(s.seconds || 0), 0);
    const invalid = V.shots.some((s) => s.seconds < MIN_S || s.seconds > MAX_S || !s.label.trim());
    const calls = V.shots.length;
    const queue = calls ? (calls - 1) * (60 / RPM) + EST_CLIP_S : 0;
    return { total, invalid, calls, queue, inr: total * USD_PER_S * USD_INR };
  }, [V.shots]);

  const setShot = (id, patch) => set({ shots: V.shots.map((s) => (s.id === id ? { ...s, ...patch } : s)) });
  const move = (i, d) => {
    const next = [...V.shots];
    const j = i + d;
    if (j < 0 || j >= next.length) return;
    [next[i], next[j]] = [next[j], next[i]];
    set({ shots: next });
  };

  const generate = async () => {
    setBusy(true);
    setError(null);
    try {
      await api.video.createReel({ shots: V.shots });
    } catch (e) {
      setError(e instanceof ApiError ? e : new ApiError(0, 'unknown', String(e)));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="flex flex-col gap-4">
      {error && <NotConnected service="Video generation" owner="Video team">The shot list, cost and queue time are real; making the clips turns on when that service is plugged in ({error.message}).</NotConnected>}
      <Banner tone="info">Offer: <strong>{sv.item}</strong>, {sv.discount} off, {sv.price}, {sv.days}. The price on screen is stamped from these approved facts by code, never generated by the video model.</Banner>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
        <section className="card">
          <CardTitle sub={`Each shot is one clip of ${MIN_S} to ${MAX_S} seconds. Clips are joined in order.`}>Shot list</CardTitle>
          <Field label="Shape"><ChipToggle multiple={false} options={ASPECTS} value={V.aspect} onChange={(v) => set({ aspect: v })} /></Field>
          <ul className="mt-4 flex flex-col gap-2">
            {V.shots.map((s, i) => {
              const bad = s.seconds < MIN_S || s.seconds > MAX_S;
              return (
                <li key={s.id} className="grid grid-cols-[auto_1fr_5.5rem_auto] items-center gap-2">
                  <span className="grid size-7 place-items-center rounded-full bg-ink/5 text-xs font-medium">{i + 1}</span>
                  <input className="field" value={s.label} onChange={(e) => setShot(s.id, { label: e.target.value })} aria-label={`Shot ${i + 1} description`} />
                  <input type="number" className={`field ${bad ? 'border-bad' : ''}`} min={MIN_S} max={MAX_S} value={s.seconds} onChange={(e) => setShot(s.id, { seconds: Number(e.target.value) })} aria-label={`Shot ${i + 1} seconds`} />
                  <span className="flex">
                    <button type="button" aria-label="Move up" onClick={() => move(i, -1)} className="grid size-8 place-items-center rounded-lg hover:bg-ink/5"><ArrowUp size={14} /></button>
                    <button type="button" aria-label="Move down" onClick={() => move(i, 1)} className="grid size-8 place-items-center rounded-lg hover:bg-ink/5"><ArrowDown size={14} /></button>
                    <button type="button" aria-label={`Remove shot ${i + 1}`} onClick={() => set({ shots: V.shots.filter((x) => x.id !== s.id) })} className="grid size-8 place-items-center rounded-lg hover:bg-ink/5"><Trash2 size={14} /></button>
                  </span>
                </li>
              );
            })}
          </ul>
          {stats.invalid && <p className="mt-2 text-xs font-medium text-bad">Each shot needs a description and {MIN_S} to {MAX_S} seconds.</p>}
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <button type="button" onClick={() => set({ shots: [...V.shots, { id: `s${Date.now()}`, label: 'New shot', seconds: 4 }] })} className="btn-ghost h-9"><Plus size={15} /> Add shot</button>
            <button type="button" disabled={busy || stats.invalid || V.shots.length === 0} onClick={generate} className="btn-primary">
              {busy ? <Loader2 size={16} className="animate-spin" /> : <Clapperboard size={16} />} Generate reel
            </button>
          </div>
        </section>

        <section className="card">
          <CardTitle sub="Free tier: video is queued at 1 request per minute.">Time and cost</CardTitle>
          <dl className="grid grid-cols-2 gap-3 text-sm">
            <div className="rounded-xl bg-ink/5 p-3"><dt className="text-xs text-ink/55">Reel length</dt><dd className="text-lg font-semibold">{stats.total}s</dd></div>
            <div className="rounded-xl bg-ink/5 p-3"><dt className="text-xs text-ink/55">Clips to make</dt><dd className="text-lg font-semibold">{stats.calls}</dd></div>
            <div className="rounded-xl bg-ink/5 p-3"><dt className="text-xs text-ink/55">Queue time (estimate)</dt><dd className="text-lg font-semibold">{formatDuration(stats.queue)}</dd></div>
            <div className="rounded-xl bg-ink/5 p-3"><dt className="text-xs text-ink/55">List price</dt><dd className="text-lg font-semibold">Rs {stats.inr.toFixed(0)}</dd></div>
          </dl>
          <p className="mt-3 text-xs text-ink/55">You pay Rs 0 while Agnes video Flash is free (720P only). The queue time uses a placeholder of {EST_CLIP_S}s per clip until the video service reports real timings.</p>
          <h3 className="mb-2 mt-5 text-sm font-semibold">Job states the service will report</h3>
          <ul className="flex flex-wrap gap-2 text-xs">{VIDEO_STATES.map((s) => <li key={s} className="rounded-full bg-ink/8 px-2.5 py-1 font-medium">{s.replace('_', ' ')}</li>)}</ul>
        </section>
      </div>

      <ContractCard title="Video service contract" request={REQUEST} response={RESPONSE} />
    </div>
  );
};

export default Video;
