"""extras: budget planner, calibration numbers, bring-your-own provider keys, offline Vosk speech-to-text.

Routes here come from the lab core in app/lab (knapsack planner, Vosk adapter, key encryption). Provider keys are
write-only: the API never returns a stored key, only its last four characters.
"""
from __future__ import annotations

import asyncio
import json
import wave
from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, File, Form, HTTPException, Request, UploadFile
from pydantic import BaseModel, Field

from app.config import ROOT
from app.db import Database
from app.lab.domain.planner import Calibration, solve
from app.lab.security import BlockedUrl, check_custom_base_url, decrypt_key, encrypt_key, last4
from app.lab.voice import vosk_stt

router = APIRouter()

CAPABILITIES = ("text", "image", "video", "stt", "tts")
SCHEMA = """
CREATE TABLE IF NOT EXISTS provider_keys (
    capability TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    base_url TEXT,
    model TEXT,
    key_enc BLOB,
    last4 TEXT,
    updated_at TEXT NOT NULL
)
"""
CALIBRATION_DIR = ROOT / "data" / "calibration"


def ensure_schema(db: Database) -> None:
    db.ensure(SCHEMA)


def key_override(db: Database, capability: str) -> str | None:
    """A key the owner saved in Settings for an Agnes capability, or None to use the server's .env key."""
    try:
        row = db.query_one("SELECT provider, key_enc FROM provider_keys WHERE capability = ?", (capability,))
    except Exception:  # noqa: BLE001 table missing in a bare test database
        return None
    if row and row["provider"] == "agnes" and row["key_enc"]:
        return decrypt_key(row["key_enc"])
    return None


def _fail(code: str, message: str, status: int = 400) -> HTTPException:
    return HTTPException(status_code=status, detail={"code": code, "message": message})


# ---------------------------------------------------------------- planner and calibration

class PlannerIn(BaseModel):
    wanted: list[dict[str, Any]] = Field(default_factory=list)
    reel_seconds: int = 0
    reels: int = 0
    limits: dict[str, float] = Field(default_factory=dict)


def latest_calibration() -> Calibration:
    """Measured RPM and latency from the newest data/calibration/agnes-*.json, else documented defaults."""
    files = sorted(CALIBRATION_DIR.glob("agnes-*.json")) if CALIBRATION_DIR.is_dir() else []
    if not files:
        return Calibration()
    try:
        data = json.loads(files[-1].read_text(encoding="utf-8"))
        calib = Calibration(source=files[-1].name)
        text = (data.get("latency_s", {}).get("copy_batch") or {}).get("p50")
        image = (data.get("image") or {}).get("seconds")
        calib.latency = {**calib.latency, **({"text": float(text)} if text else {}), **({"image": float(image)} if image else {})}
        return calib
    except (OSError, ValueError, TypeError):
        return Calibration()


@router.post("/planner/solve")
def planner_solve(body: PlannerIn) -> dict:
    # Images are generated by Agnes here (no uploaded photo), so image channels pay an image-queue charge.
    return solve(body.model_dump(), latest_calibration(), poster_uses_photo=False)


@router.get("/calibration")
def calibration() -> dict:
    calib = latest_calibration()
    return {"source": calib.source, "rpm": calib.rpm, "latency_s": calib.latency}


# ---------------------------------------------------------------- bring-your-own provider keys

class ProviderIn(BaseModel):
    provider: str = Field(min_length=1, max_length=40)
    api_key: str | None = Field(default=None, max_length=400)
    base_url: str | None = Field(default=None, max_length=300)
    model: str | None = Field(default=None, max_length=120)


def _public(row: dict[str, Any]) -> dict[str, Any]:
    return {"capability": row["capability"], "provider": row["provider"], "base_url": row["base_url"],
            "model": row["model"], "key_set": bool(row["key_enc"]), "last4": row["last4"],
            "updated_at": row["updated_at"]}


@router.get("/settings/providers")
def list_providers(request: Request) -> dict:
    db: Database = request.app.state.db
    saved = {r["capability"]: _public(r) for r in db.query("SELECT * FROM provider_keys")}
    default_key = bool(request.app.state.settings.agnes_api_key)
    out = []
    for cap in CAPABILITIES:
        out.append(saved.get(cap) or {"capability": cap, "provider": "agnes" if cap in ("text", "image", "video") else "browser",
                                      "base_url": None, "model": None, "key_set": False, "last4": None,
                                      "updated_at": None, "default": True})
    return {"providers": out, "default_agnes_key_configured": default_key,
            "stt_offline": {"engine": "vosk", "languages": sorted(vosk_stt.available_languages())}}


@router.put("/settings/providers/{capability}")
def save_provider(capability: str, body: ProviderIn, request: Request) -> dict:
    if capability not in CAPABILITIES:
        raise _fail("bad_capability", f"capability must be one of {', '.join(CAPABILITIES)}", 422)
    if body.base_url:
        try:
            check_custom_base_url(body.base_url)
        except BlockedUrl as exc:
            raise _fail("blocked_url", str(exc), 422) from exc
    db: Database = request.app.state.db
    old = db.query_one("SELECT key_enc, last4 FROM provider_keys WHERE capability = ?", (capability,))
    key_enc, tail = (old["key_enc"], old["last4"]) if old else (None, None)
    if body.api_key:  # a blank key keeps the stored one: keys are write-only, the form cannot send it back
        key_enc, tail = encrypt_key(body.api_key.strip()), last4(body.api_key.strip())
    db.execute(
        "INSERT INTO provider_keys (capability, provider, base_url, model, key_enc, last4, updated_at) "
        "VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(capability) DO UPDATE SET provider=excluded.provider, "
        "base_url=excluded.base_url, model=excluded.model, key_enc=excluded.key_enc, last4=excluded.last4, "
        "updated_at=excluded.updated_at",
        (capability, body.provider, body.base_url, body.model, key_enc, tail, datetime.now(timezone.utc).isoformat()),
    )
    return _public(db.query_one("SELECT * FROM provider_keys WHERE capability = ?", (capability,)))


@router.delete("/settings/providers/{capability}")
def reset_provider(capability: str, request: Request) -> dict:
    request.app.state.db.execute("DELETE FROM provider_keys WHERE capability = ?", (capability,))
    return {"capability": capability, "reset": True}


# ---------------------------------------------------------------- offline speech-to-text

@router.get("/stt/languages")
def stt_languages() -> dict:
    return {"engine": "vosk", "installed": vosk_stt.available_languages(),
            "unsupported": ["kn", "hinglish"],
            "note": "Vosk has no Kannada or Hinglish model. Use the browser mic or type the answer for those."}


@router.post("/stt")
async def stt(audio: UploadFile = File(...), lang: str = Form("en")) -> dict:
    data = await audio.read()
    try:
        # Vosk is CPU-bound; keep the event loop free.
        result = await asyncio.to_thread(vosk_stt.transcribe, data, lang)
    except vosk_stt.Unsupported as exc:
        raise _fail("stt_unsupported", str(exc), 422) from exc
    except (ValueError, EOFError, wave.Error) as exc:
        raise _fail("bad_audio", f"Send a 16-bit PCM WAV file ({exc}).", 422) from exc
    # The transcript is only text for the owner to correct. It never writes the locked offer facts.
    return result
